sudo: false
language: java
install:
- mvn -s .settings.xml install -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true
script:
- mvn -s .settings.xml $MVN_GOAL -nsu -Dmaven.test.redirectTestOutputToFile=true
jdk:
- oraclejdk8
env:
  global:
  - FEATURE_BRANCH=$(echo ${TRAVIS_BRANCH} | grep "^.*/.*$" && echo true || echo false)
  - INTERNAL_BUILD=$(echo ${TRAVIS_REPO_SLUG} | grep -q "^SMARTRACTECHNOLOGY/.*$"
    && echo true || echo false)
  - MVN_GOAL=$([ "${TRAVIS_PULL_REQUEST}" == "false" -a "${TRAVIS_TAG}" == "" -a "${FEATURE_BRANCH}"
    == "false" -a "${INTERNAL_BUILD}" == "true" ] && echo deploy || echo install)
  - VERSION=$(mvn validate | grep Building | head -1 | sed -e 's/.* //')
  - secure: gfkDCuagVL5QM/HpktSewRZtlOU1EJgqeui5T3HwRKTtwBjyO0g4gkhxfkdRx12Jpv98JQFupYWqHD4IUkaL22yqX3CMsbhOsCtzJb0VQrZPyaAqLIUX7nWGEu5WOEd/5p/E0TvQ0xZpc9uvmwGybbS4JhLjO5JXozNG5zU/ZFBmaxnB2QmtenXb1kx10zpft//SJRJ+FDigr5taGBPvkjO+1J1898XkEwmUfdbXLVV7nWpDIWxq/oX3zrPuh6upyMwkHRPLi/m6pe9bqb9mTZ+DsjJQHM+o/8c25XaIkCHquQqoIGiqq4EJqr0CMxv6gvNWGXUUMErGpNjK8r/ypqLToMURiBsYkxcZA2N0ocVcDtSpRmPJAcjUps6xyxcuvFr2ofDC5BzyqncPmBEPdFUlUZ28UkTD/V6o2zL9LuM7X9c4eK7X+6b3nEFrfU5/vlSBIAifgJ6LOJLGw4UYytdSS8bYR+NCIlhshN5BF28UMNZxrXgqTyEOLtejjAp4CnGphWC4Gfk2cKuwiqmuHutosDe3JoI6Qr8ectftM0Npy3IayeHAnxBpG+m0OPYcxBtISeIIAejgbBtEaz4DgBHamNJKT6GRk9TS0ipCkUedbPSJq9xyL83UFjEsguPyBMMSm5Z3qBrQNjCFooZPOyDjNxwzd2yJWMUw1rXGkX0=
  - secure: EB5QEXMzvcxnkHgsBMS5bMFIXdlBuiO/0+tqIdAOFXluN1mgwnS/xXmMxu8SEIS0BwWMzHgDRN9N2N26ehLSwE6eDNtF/a/4ip2yYSauVzCTxGVm3dZHPKKE5ASHls2XIflvk5poDBNDZn+Lk5wAQq0MYOBusA6gulxCJwl5TXk9pz/p0YPmod2C7AG6ZVOUToOZ9XNUwin4/nmk+JOAurBMtpUgzW9HyQEOCGLfoCWsFOUFbUkXrRuDRDlapaMeV9YtbnfBePeP8lwdwvPLkec1yozOODPKzhDB8t+Qx63fih3sKv6UbDz7JwjUZCD+AyZKPy0A/Y/7zW5ztYbQcOBYpBsfeuleQo4r2slcRaNm0k/EnsieDFMhIuJrc74zI4SX35JL7xD0CB+BFDmgvU0qzBd0oRzwIPckJqgQjUNLGoFaCe7ZvY+eYom0s4p49UTzphqiEx23j6f9cBY/QBVi092NdQ/Nru/vShWb5ylILtvdwneORCb+q78rI8V1Vv3UMel3USgd1UrbORfT0De+rqpRE6QlqhCOPhiyGk2yP8rBIntMNs6d5h1RwMunZY23Mc+wHfeza+O4R8dLAS5BVa6YUonEPwx3Ue3bFuk3UWDtipNy6UD8mO6gsdVyAIvWX6tVAvoIg9ORP+KfVlec/qZchAuVpY8aM4s2HIM=
notifications:
  slack:
    on_success: change
    rooms:
      secure: rwBAYNy1MInMOAAJmF8xjxcA2DAjCtjJRKMdXMXfef6eT8NM7DZ3WVPnu3HoxQdBT5bYLof6si0xeGA0w1HfUond0Kdvp88SZ/4wWmSbo2vUhWfXP4N09IUfRnfJqb7zDwVRrLRDq1sQ3vx+jXd1rKQ4jzAg2QAU1+0cL4bmCWzUuv5fSZ3oxk78P2Kr9yqpYFQ6hbEAWm88A627JZ0Qm6lL/pUGRBHTYzZmWoo26W8Fv69ZIl3w6PGirTJdCyR6xTIS2No+JXBEDZR0eIn9xkTodEIehUSt4VMC+lbzdzxHEsVdhatUfx1X8FSroiFwJIAf3GoE4rjQSiQa2KKZ/1QpWEdGxjW7q7PNlauPW7+hpj8MEqayLHeNPGEu3k2DCv3sP5oW9Hfwp2WIciNBaEw7FIhkpHQSnx9T4ySgUnulMqEZx5sqK7y6zgAU5UrA7z97DQs7ztVavsfIIhabSZHI3J2n1AOfO/4oao1jAyFOi3D3Ycs8gEx2o9vjsNeiwWfuFsOytKJacOte75oyK4kT2fsNOsLOxDaUGlCuleWbsSCne9xp10Xb/SLeW2OW7za5S807aZkGRHeVonDDcZYi+t7zD1fJMLAbcsgvYOLTE7QBUPfP3ghVHlkWKDJ6GlRnsnayNHIX6LN5g2He9Mug96Zp3IQj8odDLYRCDqY=
